# Generated by Django 3.2.7 on 2021-09-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('favorites', '0001_initial'),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='hotels',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_hotels', to='hotels.hotel'),
        ),
    ]
