# Generated by Django 3.2.7 on 2021-09-25 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20210924_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_date',
            field=models.DateField(verbose_name='Дата заезда:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_date',
            field=models.DateField(verbose_name='Дата отъезда:'),
        ),
    ]
