# Generated by Django 3.2.7 on 2021-09-25 05:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0009_auto_20210921_2320'),
        ('orders', '0021_auto_20210924_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='arrival_date',
            field=models.DateTimeField(verbose_name='Дата заезда:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='departure_date',
            field=models.DateTimeField(verbose_name='Дата отъезда:'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='hotels.hotel'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
