# Generated by Django 3.2.7 on 2021-09-26 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_auto_20210921_2320'),
        ('orders', '0030_remove_order_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='hotels.hotel'),
            preserve_default=False,
        ),
    ]
