# Generated by Django 3.2.7 on 2021-09-27 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_order_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='status',
        ),
    ]
