# Generated by Django 3.2.7 on 2021-09-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_rename_payment_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='contact_number',
            field=models.CharField(default='0', max_length=50, verbose_name='Контактный номер'),
        ),
    ]
