# Generated by Django 3.2.7 on 2021-09-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_order_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(default='', max_length=50, verbose_name='Контактный номер'),
        ),
    ]
