# Generated by Django 3.2.7 on 2021-09-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Название:')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание:')),
                ('price', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('wifi', models.CharField(choices=[('Есть', 'Есть'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=255, verbose_name='Wifi:')),
                ('parking', models.CharField(choices=[('Есть', 'Есть'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=255, verbose_name='Парковка:')),
                ('front_desk', models.CharField(choices=[('Есть', 'Есть'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=255, verbose_name='Круглосуточная стойка регистрации:')),
                ('family_rooms', models.CharField(choices=[('Есть', 'Есть'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=255, verbose_name='Семейные номера:')),
                ('non_smoking_rooms', models.CharField(choices=[('Есть', 'Есть'), ('Отсутствует', 'Отсутствует')], default='Отсутствует', max_length=255, verbose_name='Номера для некурящих:')),
                ('contact_number', models.CharField(max_length=50, verbose_name='Контактный номер')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Отели',
                'verbose_name_plural': 'Отели',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotel_image', verbose_name='Фото отеля')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_hotel', to='hotels.hotel')),
            ],
            options={
                'verbose_name': 'Лайки',
                'verbose_name_plural': 'Лайки',
                'ordering': ('-id',),
            },
        ),
    ]
