# Generated by Django 3.2.7 on 2021-09-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.TextField(),
        ),
    ]
