# Generated by Django 3.2.7 on 2021-09-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название:'),
        ),
    ]
