# Generated by Django 3.2.7 on 2021-09-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_hotel_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('-created',), 'verbose_name': 'Отели', 'verbose_name_plural': 'Отели'},
        ),
    ]
