# Generated by Django 3.2.7 on 2021-09-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_hotel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='payment',
            field=models.CharField(choices=[('USD', 'USD'), ('EURO', 'EURO'), ('KGZ', 'KGZ'), ('RUB', 'RUB')], default='USD', max_length=255, verbose_name='Оплата валюта:'),
        ),
    ]
