# Generated by Django 3.2.7 on 2021-09-22 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_alter_hotel_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='hotels_views', to='hotels.Ip'),
        ),
    ]
