# Generated by Django 3.2.7 on 2021-09-22 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_auto_20210921_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='views',
        ),
        migrations.DeleteModel(
            name='Ip',
        ),
    ]
