# Generated by Django 3.2.7 on 2021-09-27 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_remove_tag_hotels'),
        ('hotels', '0009_auto_20210921_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='tags',
            field=models.ManyToManyField(related_name='hotel_tags', to='tags.Tag'),
        ),
    ]
