# Generated by Django 3.2.7 on 2021-09-21 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Страны',
                'verbose_name_plural': 'Страны',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='CountryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='country_image', verbose_name='Фото отеля')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_image', to='countries.country')),
            ],
        ),
    ]
