# Generated by Django 3.2.7 on 2021-09-22 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.CharField(default=1, max_length=50, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
