# Generated by Django 3.2.7 on 2022-02-22 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_country_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ('-id',), 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
